// Tarsila Store — 120 apps
// Gerado automaticamente em 19/07/2026 13:47:29
window.CATALOGO_APPS = [
  {"name": "Firefox ESR", "category": "🌐 Internet", "pkg": "firefox-esr", "description": "Navegador padrão do Debian, otimizado e seguro.", "ico": "firefox-esr", "url": "https://www.mozilla.org/firefox"},
  {"name": "Chromium", "category": "🌐 Internet", "pkg": "chromium", "description": "Versão aberta do Chrome, excelente compatibilidade com a web.", "ico": "chromium", "url": "https://www.chromium.org"},
  {"name": "Falkon", "category": "🌐 Internet", "pkg": "falkon", "description": "Navegador moderno com consumo mínimo de memória (QtWebEngine).", "ico": "falkon", "url": "https://www.falkon.org"},
  {"name": "NetSurf", "category": "🌐 Internet", "pkg": "netsurf-gtk", "description": "Navegador ultra leve para leitura de notícias sem scripts pesados.", "ico": "netsurf", "url": "https://www.netsurf-browser.org"},
  {"name": "FreeTube", "category": "🌐 Internet", "pkg": "freetube", "description": "YouTube sem anúncios e sem rastreadores — versão AppImage.", "ico": "freetube", "url": "https://github.com/FreeTubeApp/FreeTube/releases/latest/download/FreeTube-linux-x86_64.AppImage"},
  {"name": "Spotify-qt", "category": "🌐 Internet", "pkg": "spotify-qt", "description": "Spotify com fração da memória do app oficial — AppImage.", "ico": "spotify-qt", "url": "https://github.com/kraxarn/spotify-qt/releases/latest/download/spotify-qt-x86_64.AppImage"},
  {"name": "ncspot", "category": "🌐 Internet", "pkg": "ncspot", "description": "Reprodutor de Spotify de altíssimo desempenho com atalhos de teclado.", "ico": "ncspot", "url": "https://github.com/hrkfdn/ncspot"},
  {"name": "Telegram Desktop", "category": "🌐 Internet", "pkg": "telegram-desktop", "description": "Mensageiro rápido e seguro para conversas e arquivos.", "ico": "telegram", "url": "https://desktop.telegram.org"},
  {"name": "Gomuks", "category": "🌐 Internet", "pkg": "gomuks", "description": "Cliente moderno e ágil para redes Matrix/Element.", "ico": "gomuks", "url": "https://github.com/tulir/gomuks"},
  {"name": "Nheko", "category": "🌐 Internet", "pkg": "nheko", "description": "Cliente Matrix/Element com interface nativa e rápida.", "ico": "nheko", "url": "https://nheko-reborn.github.io"},
  {"name": "HexChat", "category": "🌐 Internet", "pkg": "hexchat", "description": "Cliente clássico para salas de bate-papo IRC.", "ico": "hexchat", "url": "https://hexchat.github.io"},
  {"name": "Transmission", "category": "🌐 Internet", "pkg": "transmission-gtk", "description": "Cliente Torrent com interface limpa e consumo quase nulo.", "ico": "transmission", "url": "https://transmissionbt.com"},
  {"name": "Geary", "category": "🌐 Internet", "pkg": "geary", "description": "Cliente de e-mail limpo e direto para Gmail/Outlook.", "ico": "geary", "url": "https://wiki.gnome.org/Apps/Geary"},
  {"name": "Claws Mail", "category": "🌐 Internet", "pkg": "claws-mail", "description": "Cliente de e-mail ultra leve para contas corporativas.", "ico": "claws-mail", "url": "https://www.claws-mail.org"},
  {"name": "Liferea", "category": "🌐 Internet", "pkg": "liferea", "description": "Leitor de RSS para acompanhar portais sem abrir dezenas de abas.", "ico": "liferea", "url": "https://lzone.de/liferea"},
  {"name": "NewsFlash", "category": "🌐 Internet", "pkg": "newsflash", "description": "Leitor de RSS/Atom moderno com interface limpa.", "ico": "newsflash", "url": "https://gitlab.com/news-flash/news_flash_gtk"},
  {"name": "Linphone", "category": "🌐 Internet", "pkg": "linphone", "description": "Chamadas de voz e vídeo por IP (VoIP) leve.", "ico": "linphone", "url": "https://www.linphone.org"},
  {"name": "Dillo", "category": "🌐 Internet", "pkg": "dillo", "description": "Navegador minimalista focado em velocidade para páginas de texto.", "ico": "dillo", "url": "https://www.dillo.org"},
  {"name": "AbiWord", "category": "💼 Escritório", "pkg": "abiword", "description": "Substituto direto para o Word — abre .doc e .docx.", "ico": "abiword", "url": "https://www.abisource.com"},
  {"name": "Gnumeric", "category": "💼 Escritório", "pkg": "gnumeric", "description": "Substituto ágil para o Excel — abre .xlsx.", "ico": "gnumeric", "url": "https://www.gnumeric.org"},
  {"name": "Atril", "category": "💼 Escritório", "pkg": "atril", "description": "Visualizador de PDF que abre documentos instantaneamente.", "ico": "atril", "url": "https://mate-desktop.org"},
  {"name": "Qpdfview", "category": "💼 Escritório", "pkg": "qpdfview", "description": "Leitor de PDFs em abas para múltiplos artigos.", "ico": "qpdfview", "url": "https://launchpad.net/qpdfview"},
  {"name": "CherryTree", "category": "💼 Escritório", "pkg": "cherrytree", "description": "Bloco de notas hierárquico estilo Evernote/OneNote.", "ico": "cherrytree", "url": "https://www.giuspen.com/cherrytree"},
  {"name": "FocusWriter", "category": "💼 Escritório", "pkg": "focuswriter", "description": "Editor de texto em tela cheia sem distrações.", "ico": "focuswriter", "url": "https://gottcode.org/focuswriter"},
  {"name": "FeatherPad", "category": "💼 Escritório", "pkg": "featherpad", "description": "Bloco de notas moderno com abas para edições rápidas.", "ico": "featherpad", "url": "https://github.com/tsujan/FeatherPad"},
  {"name": "Osmo", "category": "💼 Escritório", "pkg": "osmo", "description": "Calendário, tarefas e contatos em uma única tela leve.", "ico": "osmo", "url": "https://sourceforge.net/projects/osmo-pim/"},
  {"name": "Orage", "category": "💼 Escritório", "pkg": "orage", "description": "Relógio de mesa e calendário com alertas.", "ico": "orage", "url": "https://www.xfce.org"},
  {"name": "RedNotebook", "category": "💼 Escritório", "pkg": "rednotebook", "description": "Diário pessoal com tags e busca rápida.", "ico": "rednotebook", "url": "https://rednotebook.sourceforge.io"},
  {"name": "Xournal++", "category": "💼 Escritório", "pkg": "xournalpp", "description": "Desenhe, assine e anote à mão sobre PDFs.", "ico": "xournalpp", "url": "https://xournalpp.github.io"},
  {"name": "Glabels", "category": "💼 Escritório", "pkg": "glabels", "description": "Crie etiquetas, cartões de visita e crachás.", "ico": "glabels", "url": "https://glabels.org"},
  {"name": "Qalculate!", "category": "💼 Escritório", "pkg": "qalculate-gtk", "description": "Calculadora financeira, científica e conversora de moedas.", "ico": "qalculate", "url": "https://qalculate.github.io"},
  {"name": "Galculator", "category": "💼 Escritório", "pkg": "galculator", "description": "Calculadora visual básica para somas rápidas.", "ico": "galculator", "url": "https://galculator.sourceforge.net"},
  {"name": "Boomaga", "category": "💼 Escritório", "pkg": "boomaga", "description": "Impressora virtual para testar layouts e economizar papel.", "ico": "boomaga", "url": "https://boomaga.github.io"},
  {"name": "Celluloid", "category": "🎬 Multimídia", "pkg": "celluloid", "description": "Reprodutor de vídeo elegante para MP4, MKV.", "ico": "celluloid", "url": "https://celluloid-player.github.io"},
  {"name": "SMPlayer", "category": "🎬 Multimídia", "pkg": "smplayer", "description": "Reprodutor completo para filmes, séries e links externos.", "ico": "smplayer", "url": "https://www.smplayer.info"},
  {"name": "MPV", "category": "🎬 Multimídia", "pkg": "mpv", "description": "Reprodutor de mídia bruto e super rápido.", "ico": "mpv", "url": "https://mpv.io"},
  {"name": "Audacious", "category": "🎬 Multimídia", "pkg": "audacious", "description": "Reprodutor de músicas estilo Winamp para coleções MP3.", "ico": "audacious", "url": "https://audacious-media-player.org"},
  {"name": "DeadBeeF", "category": "🎬 Multimídia", "pkg": "deadbeef", "description": "Player de áudio em abas para bibliotecas gigantes.", "ico": "deadbeef", "url": "https://deadbeef.sourceforge.io"},
  {"name": "Strawberry", "category": "🎬 Multimídia", "pkg": "strawberry", "description": "Organizador de áudio com capas de álbuns e letras.", "ico": "strawberry", "url": "https://www.strawberrymusicplayer.org"},
  {"name": "Sayonara Player", "category": "🎬 Multimídia", "pkg": "sayonara", "description": "Reprodutor moderno com consumo insignificante de CPU.", "ico": "sayonara", "url": "https://sayonara-player.com"},
  {"name": "Foliate", "category": "🎬 Multimídia", "pkg": "foliate", "description": "Leitor de e-books (EPUB, MOBI) mais bonito do Linux.", "ico": "foliate", "url": "https://johnfactotum.github.io/foliate"},
  {"name": "FBReader", "category": "🎬 Multimídia", "pkg": "fbreader", "description": "Leitor ágil para manuais técnicos e livros digitais.", "ico": "fbreader", "url": "https://fbreader.org"},
  {"name": "YACReader", "category": "🎬 Multimídia", "pkg": "yacreader", "description": "Leitor dedicado a HQs e mangás (CBR, CBZ).", "ico": "yacreader", "url": "https://www.yacreader.com"},
  {"name": "SimpleScreenRecorder", "category": "🎬 Multimídia", "pkg": "simplescreenrecorder", "description": "Grave a tela em vídeo sem travar a máquina.", "ico": "simplescreenrecorder", "url": "https://www.maartenbaert.be/simplescreenrecorder"},
  {"name": "Asunder", "category": "🎬 Multimídia", "pkg": "asunder", "description": "Extraia faixas de CDs e converta para MP3.", "ico": "asunder", "url": "https://littlesvr.ca/asunder"},
  {"name": "Vocal", "category": "🎬 Multimídia", "pkg": "vocal", "description": "Gerenciador para assinar, baixar e ouvir podcasts offline.", "ico": "vocal", "url": "https://vocalproject.net"},
  {"name": "Gnome Podcasts", "category": "🎬 Multimídia", "pkg": "gnome-podcasts", "description": "Podcasts com interface limpa e direta.", "ico": "gnome-podcasts", "url": "https://wiki.gnome.org/Apps/Podcasts"},
  {"name": "Xine-UI", "category": "🎬 Multimídia", "pkg": "xine-ui", "description": "Player multimídia retrô com consumo praticamente nulo.", "ico": "xine", "url": "https://xine-project.org"},
  {"name": "Pinta", "category": "🎨 Gráficos", "pkg": "pinta", "description": "Substituto do Paint.NET para recortes, setas e textos.", "ico": "pinta", "url": "https://www.pinta-project.com"},
  {"name": "LazPaint", "category": "🎨 Gráficos", "pkg": "lazpaint", "description": "Editor de imagens com camadas e efeitos, super responsivo.", "ico": "lazpaint", "url": "https://lazpaint.github.io"},
  {"name": "mtPaint", "category": "🎨 Gráficos", "pkg": "mtpaint", "description": "Pintura focado no extremo baixo consumo de memória.", "ico": "mtpaint", "url": "https://mtpaint.sourceforge.net"},
  {"name": "MyPaint", "category": "🎨 Gráficos", "pkg": "mypaint", "description": "Pintura digital com pincéis artísticos.", "ico": "mypaint", "url": "https://mypaint.org/"},
  {"name": "Drawing", "category": "🎨 Gráficos", "pkg": "drawing", "description": "O 'Microsoft Paint' do Linux com botões grandes.", "ico": "drawing", "url": "https://github.com/maoschanz/drawing"},
  {"name": "Viewnior", "category": "🎨 Gráficos", "pkg": "viewnior", "description": "Visualizador de fotos elegante que abre álbuns em frações de segundo.", "ico": "viewnior", "url": "https://siyanpanayotov.com/project/viewnior"},
  {"name": "Ristretto", "category": "🎨 Gráficos", "pkg": "ristretto", "description": "Visualizador de imagens super rápido com slideshow.", "ico": "ristretto", "url": "https://docs.xfce.org/apps/ristretto/start"},
  {"name": "Geeqie", "category": "🎨 Gráficos", "pkg": "geeqie", "description": "Organizador visual para catalogar grandes acervos de fotos.", "ico": "geeqie", "url": "https://www.geeqie.org"},
  {"name": "Mirage", "category": "🎨 Gráficos", "pkg": "mirage", "description": "Visualizador e editor para redimensionar, girar e cortar.", "ico": "mirage", "url": "https://mirageiv.sourceforge.net"},
  {"name": "Phototonic", "category": "🎨 Gráficos", "pkg": "phototonic", "description": "Visualizador com transformação e processamento em lote.", "ico": "phototonic", "url": "https://github.com/oferkv/phototonic"},
  {"name": "Dia", "category": "🎨 Gráficos", "pkg": "dia", "description": "Fluxogramas, diagramas de rede e organogramas.", "ico": "dia", "url": "https://wiki.gnome.org/Apps/Dia"},
  {"name": "GrafX2", "category": "🎨 Gráficos", "pkg": "grafx2", "description": "Estúdio de desenho em pixel art para retrogames.", "ico": "grafx2", "url": "https://github.com/grafx2/grafx2"},
  {"name": "Ksnip", "category": "🎨 Gráficos", "pkg": "ksnip", "description": "Captura de tela com setas, desfoque e salvamento rápido.", "ico": "ksnip", "url": "https://github.com/ksnip/ksnip"},
  {"name": "Nomacs", "category": "🎨 Gráficos", "pkg": "nomacs", "description": "Visualizador e editor compatível com RAW de câmeras.", "ico": "nomacs", "url": "https://nomacs.org"},
  {"name": "Drawpile", "category": "🎨 Gráficos", "pkg": "drawpile", "description": "Desenho colaborativo online com amigos em tempo real.", "ico": "drawpile", "url": "https://drawpile.net"},
  {"name": "SuperTuxKart", "category": "🎮 Games", "pkg": "supertuxkart", "description": "Corrida 3D estilo Mario Kart divertido e colorido.", "ico": "supertuxkart", "url": "https://supertuxkart.net"},
  {"name": "Minetest", "category": "🎮 Games", "pkg": "minetest", "description": "Versão open-source do Minecraft, leve com mods.", "ico": "minetest", "url": "https://www.minetest.net"},
  {"name": "SuperTux 2", "category": "🎮 Games", "pkg": "supertux", "description": "Plataforma 2D no estilo clássico do Super Mario.", "ico": "supertux", "url": "https://www.supertux.org"},
  {"name": "OpenTTD", "category": "🎮 Games", "pkg": "openttd", "description": "Simulador de transporte, ferrovias e logística.", "ico": "openttd", "url": "https://www.openttd.org"},
  {"name": "Battle for Wesnoth", "category": "🎮 Games", "pkg": "wesnoth", "description": "Estratégia em turnos e RPG em mundo medieval.", "ico": "wesnoth", "url": "https://www.wesnoth.org"},
  {"name": "Frozen Bubble", "category": "🎮 Games", "pkg": "frozen-bubble", "description": "Quebra-cabeça de atirar bolhas coloridas, viciante.", "ico": "frozen-bubble", "url": "https://www.frozen-bubble.org"},
  {"name": "Aisleriot", "category": "🎮 Games", "pkg": "aisleriot", "description": "Mais de 80 jogos de cartas (Paciência, Spider, FreeCell).", "ico": "aisleriot", "url": "https://wiki.gnome.org/Apps/Aisleriot"},
  {"name": "Pingus", "category": "🎮 Games", "pkg": "pingus", "description": "Guie pinguins construindo pontes (estilo Lemmings).", "ico": "pingus", "url": "https://pingus.seul.org"},
  {"name": "LBreakout2", "category": "🎮 Games", "pkg": "lbreakout2", "description": "Arkanoid — rebata a bolinha e destrua tijolos.", "ico": "lbreakout2", "url": "https://lgames.sourceforge.net/LBreakout2"},
  {"name": "Ri-li", "category": "🎮 Games", "pkg": "ri-li", "description": "Guie um trem de madeira para coletar vagões.", "ico": "ri-li", "url": "https://ri-li.sourceforge.net"},
  {"name": "GZDoom", "category": "🎮 Games", "pkg": "gzdoom", "description": "Motor moderno para rodar Doom com mods.", "ico": "gzdoom", "url": "https://zdoom.org"},
  {"name": "Endless Sky", "category": "🎮 Games", "pkg": "endless-sky", "description": "Exploração espacial, combate de naves e comércio 2D.", "ico": "endless-sky", "url": "https://endless-sky.github.io"},
  {"name": "Enigma", "category": "🎮 Games", "pkg": "enigma", "description": "Quebra-cabeça com bolinha de gude em labirintos.", "ico": "enigma", "url": "https://www.nongnu.org/enigma"},
  {"name": "RetroArch", "category": "🎮 Games", "pkg": "retroarch", "description": "O maior emulador de consoles (SNES, Mega Drive, GBA).", "ico": "retroarch", "url": "https://www.retroarch.com"},
  {"name": "DuckStation", "category": "🎮 Games", "pkg": "duckstation", "description": "Emulador de PlayStation 1 otimizado para ARM.", "ico": "duckstation", "url": "https://github.com/stenzek/duckstation"},
  {"name": "GCompris", "category": "🎓 Educação", "pkg": "gcompris-qt", "description": "Maior pacote educacional infantil (2 a 10 anos).", "ico": "gcompris", "url": "https://gcompris.net"},
  {"name": "TuxMath", "category": "🎓 Educação", "pkg": "tuxmath", "description": "Aprenda tabuada atirando lasers nos meteoros.", "ico": "tuxmath", "url": "https://tux4kids.github.io/tuxmath/"},
  {"name": "TuxTyping", "category": "🎓 Educação", "pkg": "tuxtyping", "description": "Ensinar a digitar com agilidade no teclado.", "ico": "tuxtyping", "url": "https://tux4kids.github.io/tuxtyping/"},
  {"name": "Childsplay", "category": "🎓 Educação", "pkg": "childsplay", "description": "Quebra-cabeças e jogos da memória para pré-escolares.", "ico": "childsplay", "url": "http://childsplay.sourceforge.net"},
  {"name": "Kanagram", "category": "🎓 Educação", "pkg": "kanagram", "description": "Jogo interativo para adivinhar e desembaraçar palavras.", "ico": "kanagram", "url": "https://kde.org/applications/education/kanagram"},
  {"name": "Anki", "category": "🎓 Educação", "pkg": "anki", "description": "Cartões de memorização com repetição espaçada.", "ico": "anki", "url": "https://apps.ankiweb.net"},
  {"name": "KGeography", "category": "🎓 Educação", "pkg": "kgeography", "description": "Aprenda países, capitais, estados e bandeiras.", "ico": "kgeography", "url": "https://kde.org/applications/education/kgeography"},
  {"name": "Stellarium", "category": "🎓 Educação", "pkg": "stellarium", "description": "Planetário 3D para explorar o céu e estrelas.", "ico": "stellarium", "url": "https://stellarium.org"},
  {"name": "Marble", "category": "🎓 Educação", "pkg": "marble", "description": "Globo terrestre virtual e atlas offline.", "ico": "marble", "url": "https://marble.kde.org"},
  {"name": "Kalzium", "category": "🎓 Educação", "pkg": "kalzium", "description": "Tabela periódica interativa com dados completos.", "ico": "kalzium", "url": "https://kde.org/applications/education/kalzium"},
  {"name": "Step", "category": "🎓 Educação", "pkg": "step", "description": "Simulador de mecânica e física interativa.", "ico": "step", "url": "https://kde.org/applications/education/step"},
  {"name": "Kig", "category": "🎓 Educação", "pkg": "kig", "description": "Geometria interativa para desenhar figuras e teoremas.", "ico": "kig", "url": "https://kde.org/applications/education/kig"},
  {"name": "SimulIDE", "category": "🎓 Educação", "pkg": "simulide", "description": "Simulador de circuitos elétricos e microcontroladores.", "ico": "simulide", "url": "https://simulide.com"},
  {"name": "OpenBoard", "category": "🎓 Educação", "pkg": "openboard", "description": "Lousa digital interativa para professores.", "ico": "openboard", "url": "https://openboard.ch"},
  {"name": "GNU Solfege", "category": "🎓 Educação", "pkg": "solfege", "description": "Treinamento de percepção auditiva para músicos.", "ico": "solfege", "url": "https://www.gnu.org/software/solfege/"},
  {"name": "Scratch 3", "category": "💻 Programação", "pkg": "scratch", "description": "Programação visual com blocos coloridos do MIT.", "ico": "scratch", "url": "https://scratch.mit.edu"},
  {"name": "Thonny", "category": "💻 Programação", "pkg": "thonny", "description": "IDE Python mais recomendada para iniciantes.", "ico": "thonny", "url": "https://thonny.org"},
  {"name": "KTurtle", "category": "💻 Programação", "pkg": "kturtle", "description": "Aprendizagem de lógica com comandos para desenhar.", "ico": "kturtle", "url": "https://kde.org/applications/education/kturtle"},
  {"name": "Geany", "category": "💻 Programação", "pkg": "geany", "description": "Editor de código e IDE rápida e leve.", "ico": "geany", "url": "https://www.geany.org"},
  {"name": "Lite XL", "category": "💻 Programação", "pkg": "lite-xl", "description": "Editor moderno em C/Lua com baixo consumo.", "ico": "lite-xl", "url": "https://lite-xl.com"},
  {"name": "Bluefish", "category": "💻 Programação", "pkg": "bluefish", "description": "Editor para desenvolvimento web (HTML/CSS/JS).", "ico": "bluefish", "url": "https://bluefish.openoffice.nl"},
  {"name": "Micro", "category": "💻 Programação", "pkg": "micro", "description": "Editor de terminal com atalhos padrão (Ctrl+C/V).", "ico": "micro", "url": "https://micro-editor.github.io"},
  {"name": "Code::Blocks", "category": "💻 Programação", "pkg": "codeblocks", "description": "IDE completa e ágil para C/C++.", "ico": "codeblocks", "url": "https://www.codeblocks.org"},
  {"name": "SciTE", "category": "💻 Programação", "pkg": "scite", "description": "Editor para arquivos enormes e compilação rápida.", "ico": "scite", "url": "https://www.scintilla.org/SciTE.html"},
  {"name": "Arduino IDE", "category": "💻 Programação", "pkg": "arduino", "description": "IDE para programar projetos de robótica.", "ico": "arduino", "url": "https://www.arduino.cc"},
  {"name": "CudaText", "category": "💻 Programação", "pkg": "cudatext", "description": "Editor multiplataforma com inicialização extrema.", "ico": "cudatext", "url": "https://cudatext.github.io"},
  {"name": "Eric IDE", "category": "💻 Programação", "pkg": "eric", "description": "IDE para Python e Ruby com interface Qt.", "ico": "eric", "url": "https://eric-ide.python-projects.org"},
  {"name": "Joe", "category": "💻 Programação", "pkg": "joe", "description": "Editor de terminal fácil de navegar.", "ico": "joe", "url": "https://joe-editor.sourceforge.io"},
  {"name": "Neovim", "category": "💻 Programação", "pkg": "neovim", "description": "Editor de código ultra rápido e extensível.", "ico": "neovim", "url": "https://neovim.io"},
  {"name": "Helix", "category": "💻 Programação", "pkg": "helix", "description": "Editor modal de alto desempenho em Rust.", "ico": "helix", "url": "https://helix-editor.com"},
  {"name": "BleachBit", "category": "🛡️ Utilitários", "pkg": "bleachbit", "description": "CCleaner do Linux — limpa caches e arquivos temporários.", "ico": "bleachbit", "url": "https://www.bleachbit.org"},
  {"name": "Gufw", "category": "🛡️ Utilitários", "pkg": "gufw", "description": "Interface visual para Firewall com botão Ligar/Desligar.", "ico": "gufw", "url": "https://gufw.org"},
  {"name": "KeePassXC", "category": "🛡️ Utilitários", "pkg": "keepassxc", "description": "Cofre digital para senhas offline e seguras.", "ico": "keepassxc", "url": "https://keepassxc.org"},
  {"name": "ClamTk", "category": "🛡️ Utilitários", "pkg": "clamtk", "description": "Antivírus visual para escanear pendrives.", "ico": "clamtk", "url": "https://clamtk.sourceforge.io"},
  {"name": "Xarchiver", "category": "🛡️ Utilitários", "pkg": "xarchiver", "description": "Gerenciador de arquivos compactados (.zip, .rar).", "ico": "xarchiver", "url": "https://xarchiver.sourceforge.net"},
  {"name": "Remmina", "category": "🛡️ Utilitários", "pkg": "remmina", "description": "Cliente para acesso remoto (RDP, VNC).", "ico": "remmina", "url": "https://remmina.org"},
  {"name": "GParted", "category": "🛡️ Utilitários", "pkg": "gparted", "description": "Utilitário para formatar e particionar discos.", "ico": "gparted", "url": "https://gparted.org"},
  {"name": "Hardinfo", "category": "🛡️ Utilitários", "pkg": "hardinfo", "description": "Informações de hardware e benchmarks.", "ico": "hardinfo", "url": "https://hardinfo.org"},
  {"name": "QDirStat", "category": "🛡️ Utilitários", "pkg": "qdirstat", "description": "Gráfico colorido mostrando o que lota o HD.", "ico": "qdirstat", "url": "https://github.com/shundhammer/qdirstat"},
  {"name": "PCManFM", "category": "🛡️ Utilitários", "pkg": "pcmanfm", "description": "Gerenciador de arquivos rápido e com abas.", "ico": "pcmanfm", "url": "https://wiki.lxde.org/en/PCManFM"},
  {"name": "Htop", "category": "🛡️ Utilitários", "pkg": "htop", "description": "Visualizador de processos e uso de RAM.", "ico": "htop", "url": "https://htop.dev"},
  {"name": "Alacritty", "category": "🛡️ Utilitários", "pkg": "alacritty", "description": "Terminal moderno acelerado por GPU.", "ico": "alacritty", "url": "https://alacritty.org"},
  {"name": "Crow Translate", "category": "🛡️ Utilitários", "pkg": "crow-translate", "description": "Tradutor instantâneo selecionando texto.", "ico": "crow-translate", "url": "https://crow-translate.github.io"},
  {"name": "KWrite", "category": "🛡️ Utilitários", "pkg": "kwrite", "description": "Bloco de notas rápido para textos simples.", "ico": "kwrite", "url": "https://kde.org/applications/utilities/kwrite"},
  {"name": "NetworkManager", "category": "🛡️ Utilitários", "pkg": "network-manager-gnome", "description": "Gerenciador de Wi-Fi para barra de tarefas.", "ico": "network-manager", "url": "https://wiki.gnome.org/Projects/NetworkManager"}
];
